#!/bin/sh
### BEGIN INIT INFO
# Provides:          iflive
# Required-Start:    $syslog $remote_fs $network
# Required-Stop:     $syslog $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the live debugging network
# Description:       naaaaaa
### END INIT INFO


PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin
SCRIPTNAME=/etc/init.d/$NAME

. /lib/lsb/init-functions

case "$1" in
    start)
	busybox ifconfig eth0 192.168.0.10 up
        ;;
    stop)
        busybox ifconfig eth0 down
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop}" >&2
        exit 1
        ;;
esac

exit 0
